"use client"

import { Card, CardContent } from "@/components/ui/card"
import type { Initiative } from "@/lib/types"
import { Building2 } from "lucide-react"
import { useStore } from "@/lib/store"

interface ReportSlideProps {
  initiatives: Initiative[]
  reportType?: string
}

export function ReportSlide({ initiatives, reportType = "quarterly" }: ReportSlideProps) {
  const { companyName } = useStore()

  // Calculate some dummy KPIs based on the initiatives
  const totalPartnerships = initiatives.reduce((acc, init) => acc + init.partners.length, 0)
  const employeeEngagement = Math.floor(Math.random() * 30) + 70 // 70-100%
  const communityImpact = Math.floor(Math.random() * 5000) + 1000 // 1000-6000
  const carbonOffset = Math.floor(Math.random() * 100) + 50 // 50-150 tons

  const currentDate = new Date()
  const quarter = Math.floor(currentDate.getMonth() / 3) + 1
  const year = currentDate.getFullYear()

  const reportTitle =
    reportType === "annual"
      ? `Annual CSR Impact Report ${year}`
      : reportType === "executive"
        ? "Executive Summary: CSR Impact"
        : reportType === "stakeholder"
          ? "Stakeholder CSR Update"
          : `Q${quarter} ${year} CSR Impact Report`

  return (
    <div className="aspect-video bg-white rounded-lg overflow-hidden border shadow-sm">
      <div className="h-full flex flex-col">
        {/* Header */}
        <div className="bg-emerald-600 text-white p-6">
          <div className="flex justify-between items-center">
            <div>
              <h2 className="text-2xl font-bold">{reportTitle}</h2>
              <p className="text-emerald-100">Making a difference through strategic initiatives</p>
            </div>
            <div className="flex items-center gap-2">
              <Building2 className="h-8 w-8" />
              <span className="text-xl font-bold">{companyName || "Acme Corp"}</span>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 p-6 flex flex-col">
          {/* KPIs */}
          <div className="grid grid-cols-4 gap-4 mb-6">
            <Card>
              <CardContent className="p-4 flex flex-col items-center justify-center">
                <p className="text-3xl font-bold text-emerald-600">{initiatives.length}</p>
                <p className="text-sm text-slate-600 text-center">Active Initiatives</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-4 flex flex-col items-center justify-center">
                <p className="text-3xl font-bold text-emerald-600">{totalPartnerships}</p>
                <p className="text-sm text-slate-600 text-center">Partner Organizations</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-4 flex flex-col items-center justify-center">
                <p className="text-3xl font-bold text-emerald-600">{employeeEngagement}%</p>
                <p className="text-sm text-slate-600 text-center">Employee Engagement</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-4 flex flex-col items-center justify-center">
                <p className="text-3xl font-bold text-emerald-600">{communityImpact}</p>
                <p className="text-sm text-slate-600 text-center">Community Members Impacted</p>
              </CardContent>
            </Card>
          </div>

          {/* Initiatives Summary */}
          <h3 className="text-lg font-semibold mb-3">Initiative Highlights</h3>
          <div className="grid grid-cols-1 gap-3">
            {initiatives.map((initiative, index) => (
              <div key={index} className="flex items-start gap-3 p-3 bg-slate-50 rounded-md">
                <div className="h-8 w-8 rounded-full bg-emerald-100 flex items-center justify-center text-emerald-700 font-medium">
                  {index + 1}
                </div>
                <div className="flex-1">
                  <div className="flex justify-between items-start">
                    <div>
                      <p className="font-medium">{initiative.name}</p>
                      <p className="text-sm text-slate-600">
                        Partnered with {initiative.partners.join(", ")} • {initiative.theme}
                      </p>
                    </div>
                    <div className="bg-emerald-50 text-emerald-700 px-2 py-1 rounded text-xs font-medium">
                      {Math.floor(Math.random() * 80) + 20}% Complete
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Footer */}
          <div className="mt-auto pt-4 text-center text-sm text-slate-500">
            Generated by MandelaOS • Autonomous CSR Department
          </div>
        </div>
      </div>
    </div>
  )
}
